# Usa una imagen de Python ligera
FROM python:3.11-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia el requirements.txt desde el directorio backend
COPY backend/requirements.txt .

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copia todo el directorio backend
COPY backend backend/

# Expone el puerto que usará la API
EXPOSE 8000

# Comando para ejecutar la aplicación
CMD ["uvicorn", "backend.backend:app", "--host", "0.0.0.0", "--port", "8000"]